using System;
using System.Collections.Generic;
using Boomerang2DFramework.Framework.Actors;
using Boomerang2DFramework.Framework.MapGeneration;
using Boomerang2DFramework.Framework.StateManagement;
using Boomerang2DFramework.Framework.Utilities;
using UnityEngine;

namespace Boomerang2DFramework.Framework.Camera {
	/// <summary>
	/// MonoBehavior that controls the Camera's behavior. 
	/// </summary>
	/// <remarks>
	/// The CameraController doesn't render a camera directly to the viewport. Instead, it manages a collection
	/// of RenderTextures generated by LayerCameraControllers, and renders each of those RenderTextures to the
	/// GUI Layer on each frame. 
	/// </remarks>
	public class CameraController : MonoBehaviour {
		public Actor Target;
		public MapViewBehavior CurrentView;
		public Vector3 RealPosition;
		public Vector3 DestinationPosition;
		public float HorizontalLerpSpeed;
		public float VerticalLerpSpeed;
		public float OrthographicSize;
		public float Aspect;

		public StateMachine StateMachine;

		private Texture2D _backdrop;

		private readonly Dictionary<string, MapCameraLayer> _mapCameraLayers = new Dictionary<string, MapCameraLayer>();
		private readonly Dictionary<string, RenderTexture> _uiCameraLayers = new Dictionary<string, RenderTexture>();

		private struct MapCameraLayer {
			public MapLayerBehavior MapLayerBehavior;
			public RenderTexture RenderTexture;
		}

		private Vector3 _velocity = Vector3.zero;

		private void Start() {
			StateMachine = new StateMachine();
			OrthographicSize = GameProperties.DefaultCameraSize;
			Aspect = GameProperties.AspectRatio;
			BuildBackdropTexture();
		}

		private void LateUpdate() {
			if (Target == null) {
				return;
			}

			StateMachine.ProcessSetUpFrameState();
			StateMachine.UpdateState();
			StateMachine.ProcessState();

			LerpToDestinationPosition();
			UpdateMapLayerCameras();

			StateMachine.ProcessPostFrameState();
		}

		private void LerpToDestinationPosition() {
			RealPosition = new Vector3(
				Vector3.SmoothDamp(
					RealPosition,
					DestinationPosition,
					ref _velocity,
					HorizontalLerpSpeed * GameProperties.PixelSize
				).x,
				Vector3.SmoothDamp(
					RealPosition,
					DestinationPosition,
					ref _velocity,
					VerticalLerpSpeed * GameProperties.PixelSize
				).y,
				RealPosition.z
			);

			transform.localPosition = BoomerangUtils.RoundToPixelPerfection(RealPosition);
		}

		private void UpdateMapLayerCameras() {
			foreach (KeyValuePair<string, MapCameraLayer> mapCameraLayer in _mapCameraLayers) {
				mapCameraLayer.Value.MapLayerBehavior.UpdateLayerCameraPosition();
			}
		}

		public void SetCurrentView(MapViewBehavior newView) {
			if (CurrentView == newView) {
				return;
			}

			if (CurrentView) {
				CurrentView.DefaultCameraState.OnExitState();
			}

			CurrentView = newView;
			newView.DefaultCameraState.OnEnterState();
			StateMachine.SetNextState(newView.DefaultCameraState);
		}


		public void AddMapLayerRender(string mapName, MapLayerBehavior mapLayerBehavior, RenderTexture renderTexture) {
			_mapCameraLayers.Add(mapName, new MapCameraLayer {
				MapLayerBehavior = mapLayerBehavior,
				RenderTexture = renderTexture
			});
		}

		public void AddUiLayerRender(string hudObjectName, RenderTexture renderTexture) {
			_uiCameraLayers.Add(hudObjectName, renderTexture);
		}

		public void ClearAllMapLayers() {
			_mapCameraLayers.Clear();
		}

		public void ClearUiLayer(string hudObjectName) {
			_uiCameraLayers.Remove(hudObjectName);
		}

		/// <summary>
		/// Renders all the LayerCamera RenderTextures to the screen
		/// </summary>
		private void OnGUI() {
			RenderBackdrop();

			GUI.BeginGroup(new Rect(0, 0, Screen.width, Screen.height));
			foreach (KeyValuePair<string, MapCameraLayer> mapCameraLayer in _mapCameraLayers) {
				RenderLayer(mapCameraLayer.Value.RenderTexture);
			}

			foreach (KeyValuePair<string, RenderTexture> uiCameraLayer in _uiCameraLayers) {
				RenderLayer(uiCameraLayer.Value);
			}

			GUI.EndGroup();
		}

		private void BuildBackdropTexture() {
			Color32[] backdropColor = {Color.black};
			_backdrop = new Texture2D(1, 1);
			_backdrop.SetPixels32(backdropColor);
			_backdrop.Apply();
		}

		private void RenderBackdrop() {
			Graphics.DrawTexture(new Rect(0, 0, Screen.width, Screen.height), _backdrop);
		}

		private void RenderLayer(RenderTexture renderTexture) {
			float scaleX = Screen.width / (float) GameProperties.RenderDimensionsWidth;
			float scaleY = Screen.height / (float) GameProperties.RenderDimensionsHeight;

			Rect screenRenderRect = new Rect();

#pragma warning disable 0162
			switch (GameProperties.RenderDisplayMode) {
				case RenderDisplayMode.PixelPerfect:
					float maxScale = scaleX < scaleY
						? scaleX
						: scaleY;

					maxScale = Mathf.FloorToInt(maxScale);
					maxScale = BoomerangUtils.MinValue(maxScale, 1);
					screenRenderRect.width = GameProperties.RenderDimensionsWidth * maxScale;
					screenRenderRect.height = GameProperties.RenderDimensionsHeight * maxScale;
					break;
				case RenderDisplayMode.Stretch:
					screenRenderRect.width = Screen.width;
					screenRenderRect.height = Screen.height;
					break;
				case RenderDisplayMode.Fit:
					screenRenderRect.width = scaleX > scaleY
						? Screen.height * GameProperties.AspectRatio
						: Screen.width;

					screenRenderRect.height = scaleX > scaleY
						? Screen.height
						: Screen.width / GameProperties.AspectRatio;
					break;
				default:
					throw new ArgumentOutOfRangeException();
			}
#pragma warning restore 0162

			if (screenRenderRect.width < Screen.width) {
				screenRenderRect.x = (Screen.width - screenRenderRect.width) / 2;
			}

			if (screenRenderRect.height < Screen.height) {
				screenRenderRect.y = (Screen.height - screenRenderRect.height) / 2;
			}

			Graphics.DrawTexture(screenRenderRect, renderTexture);
		}
	}
}